### ISSUE TITLE
Trying to locate papertrail-rsyslog/papertrail-rsyslog.tar.gz

### ISSUE THREAD

**Issue by vipulnsward** [hipsnip-cookbooks/papertrail-rsyslog#7]
Hello, I am trying to locate where or how papertrail-rsyslog/papertrail-rsyslog.tar.gz gets downloaded when installing this cookbook. For me with a slow internet, this hogs down the process, for an hour when used with chef-solo.

Any pointers would be helpful, to bring this time down.

**Comment by motns** [comment]
Hi there,

I'd imagine it gets downloaded from Chef Supermarket. Looking at the [cookbook page](https://supermarket.chef.io/cookbooks/papertrail-rsyslog) the download link points to Amazon S3.
I did download it and it appears to be way too big for a cookbook (~40MB). Looking at the extracted contents, there's an extra (seemingly corrupted) archive file in there, probably included by accident. I no longer maintain this cookbook, so unfortunately I can't fix this directly... I have transferred ownership a while back to this guy:
https://github.com/widgit-cookbooks/papertrail-rsyslog

You'll want to get in touch with him to get this fixed.

Thanks,
Adam

**Comment by vipulnsward** [comment]
Yes, found the reason. Was able to avoid it by pointing to Github repo
instead. I triedreporting to  new repo but github dint allow me to create
an issue there.

On Monday, April 27, 2015, Adam Borocz notifications@github.com wrote:

> Closed #7
> https://github.com/hipsnip-cookbooks/papertrail-rsyslog/issues/7.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/hipsnip-cookbooks/papertrail-rsyslog/issues/7#event-290887314
> .

## 

Vipul A.M.
+91-8149-204995
